### ISSUE TITLE
Sync extensions installed in VSCode server on jupyterlab images to those in remote desktop

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/aaw-kubeflow-containers#172]
VSCode experiences should be as linked as possible

**Comment by blairdrummond** [comment]
@ca-scribner  I think we have VS Code installed in JupyterLab and Remote Desktop separately atm; we could show people the mixin approach to have a "single ground truth" for VS Code install

**Comment by blairdrummond** [comment]
Maybe we could rename the issue to reflect that?

**Comment by ca-scribner** [comment]
I think that would be a great idea now that they’re all in one repo!
