### ISSUE TITLE
docs: conda notebooks

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/aaw-kubeflow-containers#179]
To add a conda environment as a jupyter kernel, you just need to do `conda install ipykernel` within that conda env.

I was not aware of this, but we should document it

**Comment by ca-scribner** [comment]
does this automate the update to jupyterlab?  I thought there was another command or two needed afterwards

**Comment by ca-scribner** [comment]
I expected something else like this required:
```
ipython kernel install --name "local-venv"
```
(might have the syntax a little off)

**Comment by Souheil-Yazji** [comment]
Stale Issue.
