### ISSUE TITLE
Jupyter widgets not fully translated

### ISSUE THREAD

**Issue by Jose-Matsuda** [StatCan/aaw-kubeflow-containers#269]
Lower priority / not fixed yet as the priority was **coverage** Can extend to fr-CA later as it is needed
Another small issue branch off of StatCan/kubeflow-containers-desktop#48 and some info in the [pr](https://github.com/StatCan/kubeflow-containers-desktop/pull/52)
Currently if the user is using "French (Canada)" in their browser some hover-over text of a few widgets are not translated. The user needs to be in "French (France)"
![image](https://user-images.githubusercontent.com/23174198/103684410-83643c00-4f59-11eb-8b46-05688328c79e.png)

Video [here](https://youtu.be/QPsvuDbu3mY) at 29 seconds

It must be in fr_FR because Jupyter does not have a fr_CA translation, only a fr_FR. I'm surprised that it is not smart enough to just use fr_FR if fr_CA is found in either the environment variable or as the browser language.

This problem mainly exists in Chromium as in Firefox, there is one 'French' option and with that option the hover-over is translated.

**Comment by mathis-marcotte** [comment]
Closing this issue as it is now either fixed or irrelevant.
