### ISSUE TITLE
kubectl does not work from RStudio notebook's terminal

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/aaw-kubeflow-containers#272]
In an RStudio notebook server, typing `kubectl get pods` (or anything else) returns:
```
(base) jovyan@rspi-0:~$ kubectl get pods
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

I believe `kubectl` returns that when it tries to use the default `localhost:8080` (because no other context is set) and is rejected.  

Oddly, this works fine if you:
* connect to the RStudio pod using `kubectl exec -it REMOTE_DESKTOP_POD -c REMOTE_DESKTOP_CONTAINER -- bash` and run `kubectl get pods`
* try `kubectl` from the RStudio terminal **in the remote desktop image**

**Comment by ca-scribner** [comment]
@blairdrummond made a good point about environment variables in the RStudio terminal.  I compared a jupyterlab terminal to the RStudio terminal and there are a number of `KUBERNETES_*` variables in the jupyterlab that are not in the RStudio one.  I thought they might be how kubectl knows where to talk with, adding them to the RStudio terminal manually didn't help

**Comment by ca-scribner** [comment]
Correction, adding them with `export` **does** fix `kubectl`.  Doing this in a RStudio terminal works:
```
export KUBERNETES_PORT_443_TCP_ADDR=10.0.0.1
export KUBERNETES_PORT_443_TCP_PORT=443
export KUBERNETES_PORT_443_TCP_PROTO=tcp
export KUBERNETES_PORT_443_TCP=tcp://10.0.0.1:443
export KUBERNETES_PORT=tcp://10.0.0.1:443
export KUBERNETES_SERVICE_HOST=10.0.0.1
export KUBERNETES_SERVICE_PORT=443
export KUBERNETES_SERVICE_PORT_HTTPS=443
kubectl get pods
```

**Comment by rohank07** [comment]
*update
export KUBERNETES_SERVICE_PORT=443
export KUBERNETES_SERVICE_PORT_HTTPS=443
export KUBERNETES_PORT_443_TCP=tcp://10.135.0.1:443
export KUBERNETES_PORT_443_TCP_PROTO=tcp
export KUBERNETES_PORT_443_TCP_ADDR=10.135.0.1
export KUBERNETES_SERVICE_HOST=10.135.0.1
export KUBERNETES_PORT=tcp://10.135.0.1:443
export KUBERNETES_PORT_443_TCP_PORT=443
