### ISSUE TITLE
Switch from internal jfrom url to external url

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/aaw-kubeflow-containers#322]
We identified the issue that made us use the internal URL originally, and now have that fixed.

We should configure conda and pip to pull from the external URL instead, and this will fix the dev cluster in the process.

**NOTE: the issue was fixed by editing the coredns configmap in the kube-system namespace**

**Comment by blairdrummond** [comment]
Closed by https://github.com/StatCan/aaw-kubeflow-containers/pull/323

**Comment by chuckbelisle** [comment]
usual AAW URL format ;-)
