### ISSUE TITLE
Add SAS and SAS Studio IDE

### ISSUE THREAD

**Issue by sylus** [StatCan/aaw-kubeflow-containers#330]
# Description

Addition of SAS for CLI, SASPY for Notebooks, and SAS Studio (Web IDE).

> **Note**: I use another base container to grab the SAS F.S. where as the base container grabbed the SAS F.S. from an azure share but in order to not leak credentials this was the best method and also faster in CI due to docker compression.

> **Note**: SAS alone is about 6GB so the full container image is 12.0GB at the moment.

# Remaining Tasks

- [x] Using custom extension of jupyter-server-proxy add a button which will allow for a user to launch SAS Studio IDE
- [x] Resolve authorization issue by correctly setting cookie for SAS Studio IDE using the custom extension
- [ ] Add CI step
- [x] Add GateKeeper Policy to restrict to StatCan employees

# Custom Extension

All the custom extension needs to do is call the following script when the button is clicked:

```sh
/usr/local/SASHome/studioconfig/sasstudio.sh start
```

Along with forwarding to the correct address:

```
http://127.0.0.1:8888/notebook/username/notebookname/proxy/38080/SASStudio/
```

## Quick Documentation

> **Note**: Reminder that important files can be saved in your Azure Files remote mount.

### Environment Launch Screen

Eventually the custom image will appear in the drop down on the preceding screen but for now this is the post selection screen showing that we selected the SAS container and gave it 1 CPU and 4 GB memory.

<img width="937" alt="01-select-environment" src="https://user-images.githubusercontent.com/984304/157108138-0c0bcebc-9e82-4329-a3a5-89bb31792194.png">

<img width="1362" alt="02-launch-screen" src="https://user-images.githubusercontent.com/984304/157109751-8c3c793a-d480-41d5-b4bc-abe49d8c453c.png">

### SASPY with Notebooks

SAS Kernel through SASpy allows a python process to connect to SAS 9.4 and run SAS code, generated by the supplied object and methods or explicitly user written, and returns results as text, HTML5 documents (via SAS ODS), or as Pandas Data Frames. It supports running analytics and returning the resulting graphics and result data. It can convert between SAS Data Sets and Pandas Data Frames. It has multiple access methods which allow it to connect to local or remote Linux SAS, IOM SAS on Windows or Linux (Including Grid Manager), and local PC SAS. It can run w/in Jupyter Notebooks, in line mode python or in python batch scripts.

```sh
title "Stock High, Low, and Close";

proc sgplot data=sashelp.stocks;
  where Date >= '01JAN2005'd and stock='IBM';
  highlow x=date high=high low=low / close=close;
run;

title;
```

<img width="1876" alt="03-sas-notebook" src="https://user-images.githubusercontent.com/984304/157109998-3373d503-866e-4549-8382-dc3461bde16d.png">

### SAS Studio

We also added the option for launching SAS Studio all accomplished by just clicking the button in the launch screen.

Please note it is a little slow to start up but this is normal though for performance might need to give more then 1 CPU.

<img width="1085" alt="04-sas-studio" src="https://user-images.githubusercontent.com/984304/157110438-32606cae-eac4-41b4-bf0f-8eac9fae8012.png">

## Links

- [SASPY](https://github.com/sassoftware/saspy)
- [SAS for Containers](https://www.sas.com/en_us/solutions/cloud/for-containers.html)
- [Whitepaper](https://www.sas.com/content/dam/SAS/documents/briefs/solution-brief/en/sas-for-containers-109970.pdf)
- [Technical Paper](https://support.sas.com/content/dam/SAS/support/en/technical-papers/understanding-containers-sas-9-4-container-deployment.pdf)

**Comment by brendangadd** [comment]
@sylus Does the container have CI into ACR? Can we close this? The other tasks are tracked in StatCan/daaas#918

**Comment by sylus** [comment]
@blairdrummond is the gatekeeper policy all good now?

**Comment by sylus** [comment]
@blairdrummond you said would add the CI step or want me to?
