### ISSUE TITLE
Update vscode/code-server

### ISSUE THREAD

**Issue by Jose-Matsuda** [StatCan/aaw-kubeflow-containers#337]
Currently we use a fork here https://github.com/StatCan/aaw-kubeflow-containers/blob/96c3c587854fa892b84ba83d2fad35c60942f65c/docker-bits/6_jupyterlab.Dockerfile#L16

I think the reason for this initially was to block the download https://github.com/StatCan/aaw-kubeflow-containers/pull/281.

There has been action upstream in an issue [upstream](https://github.com/coder/code-server/issues/2426) so maybe we'll be able to switch back at some point

As for remote desktop we do use original [vscode](https://github.com/StatCan/aaw-kubeflow-containers/blob/96c3c587854fa892b84ba83d2fad35c60942f65c/scripts/remote-desktop/vs-code-desktop.sh#L14) and should get around to updating this as well.

In both cases may need to upgrade the French `.vsix` files for both

Might actually be a `size/M` but just update if necessary

**Comment by Souheil-Yazji** [comment]
It seems that the option to disable download is enabled via a CLI command flag. I'm not sure how code-server is integrated on jupyterlab notebooks and whether or not it's possible to configure the vs code-server launcher. If it is, we may be able to use an env variable to assign a value for the `--disable-file-downloads` flag depending on the notebook type (pro-b vs unc)
