### ISSUE TITLE
JupyterLab notebooks do not source .bashrc for new shell.

### ISSUE THREAD

**Issue by Jose-Matsuda** [StatCan/aaw-kubeflow-containers#364]
Came as a result of testing https://github.com/StatCan/aaw-kubeflow-containers/pull/360

When scheduled to a GPU node, the `.bashrc` or the ["shell_helpers"](https://github.com/StatCan/aaw-kubeflow-containers/blob/dadf71098b9cdb57ce856689ca2630b7d67c6f87/resources/common/shell_helpers.sh#L6) bit is not ran at terminal startup.

As in the following screen _does not appear_
![image](https://user-images.githubusercontent.com/23174198/174631418-27678973-80b3-4f6a-8cc2-06f07d48290e.png)

When Bhavika was testing her changes the `base` with a notebook scheduled to a gpu machine she was unable to do any `conda activate torch` and had to do `source .bashrc` before being able to successfully run her testing.

**Comment by bryanpaget** [comment]
`echo $SHELL` returns `/bin/bash`. 

Manually calling `bash` and `zsh` shows the welcome message.

![image](https://user-images.githubusercontent.com/8212170/176697008-82041b13-5eb9-424b-831d-3b9d5c39f9b7.png)

**Comment by bryanpaget** [comment]
I've created a pull request which adds the `.profile` to the JupyterLab Dockerfile.

**Comment by bryanpaget** [comment]
I was able to test my changes on a GPU node:

![Image](https://user-images.githubusercontent.com/8212170/185995083-91acbb5b-e672-4994-99da-574c15014d88.png)

I am able to `conda activate torch`.

**Comment by bryanpaget** [comment]
I also just tested my changes in the JupyterLab Tensorflow image. Everything works!

![Image](https://user-images.githubusercontent.com/8212170/185999291-f2553e2f-21a1-40cb-a70f-f0df626fa91b.png)
