### ISSUE TITLE
Remote-desktop build failing

### ISSUE THREAD

**Issue by bsewp045** [StatCan/aaw-kubeflow-containers#366]
The remote-desktop image is successfully built but step "Run Azure/container-scan@v0" is failing in git actions.

<img width="639" alt="errorremote" src="https://user-images.githubusercontent.com/59851256/175300281-0fff44ce-14c5-4906-9b13-6b27b30fbc99.PNG">

[build_and_push #889](https://github.com/StatCan/aaw-kubeflow-containers/actions/runs/2545152895)

**Comment by Jose-Matsuda** [comment]
Should be able to close this as we moved off of `Azure/containerscan` in https://github.com/StatCan/aaw-kubeflow-containers/issues/380
