### ISSUE TITLE
Investigate issues with Rmd on the AAW

### ISSUE THREAD

**Issue by bryanpaget** [StatCan/aaw-kubeflow-containers#377]
When trying to knit an Rmd document in RStudio on the AAW, I get the following error:

![image](https://user-images.githubusercontent.com/8212170/183664655-a122d6bd-d57a-46fe-b6c1-8f9bed32edf1.png)

**Note:** The following is related but does not fix our issue: https://github.com/r-lib/devtools/issues/406

Investigate the status of creating and rendering Rmd documents on the AAW using the RStudio image.

**Comment by bryanpaget** [comment]
I'm not getting this error as of now.

I am able to knit the following document:

https://github.com/bryanpaget/Toronto-Cycling-Traffic-and-Bikeway-Open-Data

However, I needed to install a few packages

- rgeos
- rgdal
- raster

`conda install -c r r-rgeos r-rgdal raster`

**Comment by bryanpaget** [comment]
I'll make a list of the packages I need to install on a fresh RStudio image before I can build an Rmd document.

1. Markdown

![Image](https://user-images.githubusercontent.com/8212170/228063180-0926a7eb-262e-4fb5-a11e-9e7eddbd9519.png)

**Comment by bryanpaget** [comment]
I am able to render Quarto projects and knit Rmd documents. Therefore I believe this issue is no longer an issue. For instance I can consistently knit the following Rmd document:

```
---
title: "Diamond sizes"
date: 2016-08-25
output: html_document
---

```{r setup, include = FALSE}
library(ggplot2)
library(dplyr)

smaller <- diamonds %>% 
  filter(carat <= 2.5)
```

We have data about `r nrow(diamonds)` diamonds. Only 
`r nrow(diamonds) - nrow(smaller)` are larger than
2.5 carats. The distribution of the remainder is shown
below:

```{r, echo = FALSE}
smaller %>% 
  ggplot(aes(carat)) + 
  geom_freqpoly(binwidth = 0.01)
```
```

**Comment by bryanpaget** [comment]
I am going to update all R packages using the menu **Tools > Check for Packages Updates...** and see what happens.

**Comment by bryanpaget** [comment]
This error message continues to appear:

![Image](https://user-images.githubusercontent.com/8212170/229206164-53daacb0-cd05-44c6-8ff5-b7ccd9ff35a7.png)

The package `markdown` has been installed as noted above.

**Comment by bryanpaget** [comment]
I installed `markdown` with Resolved with `install.packages("markdown")` and I am able to knit documents once again. I'm going to reboot the container and see if the problem remains solved or reappears.

**Comment by bryanpaget** [comment]
Rebooting the container causes the problem to return.

**Comment by bryanpaget** [comment]
I'm going to try manually installing `janitor`, `raster`, `rgdal`, `rgeos`.

> install.packages(c("janitor", "raster", "rgdal", "rgeos"))
Error in install.packages : Updating loaded packages
> install.packages(c("janitor", "raster", "rgdal", "rgeos"))
also installing the dependencies ‘Rcpp’, ‘snakecase’, ‘sp’, ‘terra’

**Comment by bryanpaget** [comment]
`terra` and therefore `raster` cannot be installed:

```
ERROR: dependency ‘terra’ is not available for package ‘raster’
* removing ‘/opt/conda/lib/R/library/raster’
Warning in install.packages :
  installation of package ‘raster’ had non-zero exit status
```

**Comment by bryanpaget** [comment]
`rgdal` also fails

```
configure: error: GDALAllRegister not found in libgdal.
ERROR: configuration failed for package ‘rgdal’
* removing ‘/opt/conda/lib/R/library/rgdal’
Warning in install.packages :
  installation of package ‘rgdal’ had non-zero exit status
```

**Comment by bryanpaget** [comment]
We seem to have an issue with packages, perhaps installing the above packages with `conda` will make a difference.

**Comment by bryanpaget** [comment]
## Summary of Investigation

- `markdown` needs to be installed when creating a new container
- `markdown` needs to be reinstalled ever time the container is restarted
- Quarto document creation does not seem to be affected

**Comment by bryanpaget** [comment]
Next Sprint:

This ticket has uncovered a different issue than was originally reported. Next sprint I'll investigate

1. Why `markdown` is not installed by default.
2. Why package installation is not persisting across reboots

**Comment by Souheil-Yazji** [comment]
It's possible that the packages aren't being persisted correctly since [the package manager dir /opt/rstudio-pm](https://docs.posit.co/rspm/admin/file-storage/file-storage/#program-files) isn't mounted to a PV

**Comment by bryanpaget** [comment]
Work will continue next sprint, see #472.
