### ISSUE TITLE
Depricate Fork Statcan/code-server

### ISSUE THREAD

**Issue by Souheil-Yazji** [StatCan/aaw-kubeflow-containers#392]
This repo is no longer in use due to #375 and can be archived.
https://github.com/StatCan/code-server

**Comment by Souheil-Yazji** [comment]
@chuckbelisle can we archive [this repo](https://github.com/StatCan/code-server) please

**Comment by chuckbelisle** [comment]
Yes we can archive, unfortunetly I do not have access to do that. It was originally forked by @rohank07

**Comment by rohank07** [comment]
This wasn't forked by me - I don't have permissions to fork it either.

**Comment by Souheil-Yazji** [comment]
I think it would be forked under the statcan organization: `You can delete any repository or fork if you're either an organization owner or have admin permissions for the repository or fork`

**Comment by chuckbelisle** [comment]
@sylus could you please archive the following repo https://github.com/StatCan/code-server? It is no longer used in AAW and we would like it cleaned if possible.

Thanks!

**Comment by sylus** [comment]
Done! @chuckbelisle
