### ISSUE TITLE
Jfrog: Change the URL to be internal service

### ISSUE THREAD

**Issue by Jose-Matsuda** [StatCan/aaw-kubeflow-containers#428]
Maybe I'm misunderstanding things / forgot something, but for whatever reason (and it's been working just fine) the url we have configured is 
https://github.com/StatCan/aaw-kubeflow-containers/blob/ed7999fb8cba371f4fbb0334460096834ca78977/output/jupyterlab-cpu/pip.conf#L3

Should this instead be a `.svc.cluster.local` URL?

Note that we may move to cloud main artifactory and as it stands this currently works so this may just end up being closed.

**Comment by Souheil-Yazji** [comment]
Stale.
