### ISSUE TITLE
Update vs code version in remote desktop image

### ISSUE THREAD

**Issue by mathis-marcotte** [StatCan/aaw-kubeflow-containers#432]
We are currently installing visual studio code v1.46.0 in the remote desktop image. That version is more than 2 years old. So it might be a good idea to update to a more current version.

**Comment by Jose-Matsuda** [comment]
Also will need to update the French language pack probably

**Comment by mathis-marcotte** [comment]
Updated vs code version 
![image](https://user-images.githubusercontent.com/84033116/216656110-c426e57a-e442-476b-bbaf-85214ae440bf.png)
