### ISSUE TITLE
Investigate and Update packages 

### ISSUE THREAD

**Issue by Jose-Matsuda** [StatCan/aaw-kubeflow-containers#453]
We should update any packages that we have installed ourselves and possibly look at updating the packages we get from upstream.

Related to https://github.com/StatCan/daaas-private/issues/58

**Comment by chuckbelisle** [comment]
@wg102 helping out with this for Sprint50

**Comment by wg102** [comment]
All notes were kept in the private issue https://github.com/StatCan/daaas-private/issues/58

**Comment by Jose-Matsuda** [comment]
Closed by https://github.com/StatCan/aaw-kubeflow-containers/pull/463
