### ISSUE TITLE
Add simple bash script to suspend current server to all images

### ISSUE THREAD

**Issue by StanHatko** [StatCan/aaw-kubeflow-containers#459]
Using kubectl it's possible to suspend the current notebook server, which is useful at the end of a long running job (especially overnight / over-the-weekend jobs) to stop the server and avoid running costs while the server sits idle. However this requires a rather long command which needs to be customized per-server with the server name and namespace name.

Using the following bash script it's possible to automatically shut down the current notebook server:

```
#!/bin/bash
nb_server_name=`echo $NB_PREFIX | perl -pe 's/^.*\///'`
tag_date=`date +%Y-%m-%d"T"%H:%M:%SZ`
echo "Shutting down server named $nb_server_name in namespace $NB_NAMESPACE with date tag $tag_date."
kubectl annotate notebook/$nb_server_name kubeflow-resource-stopped=$tag_date -n $NB_NAMESPACE
echo "Command had return code $?."
```

I called it `aaw-suspend-server.sh`, making it executable and running `./aaw-suspend-server.sh` automatically shut down the currently running notebook server. By adding this to the images (in /usr/bin or similar) we can give users a simple standard way to shut down the currently running notebook server once the job completes, simply by running aaw-suspend-server.sh at the end of the run.

**Comment by rohank07** [comment]
Merged in. Waiting image to be built and pushed by CI. 
The script exists at `/usr/local/bin` and can be called from anywhere
