### ISSUE TITLE
Suggestion: switch from conda to mamba

### ISSUE THREAD

**Issue by bryanpaget** [StatCan/aaw-kubeflow-containers#483]
Mamba is a much improved package manager for Anaconda. The conda package manager tends to be painfully slow, often stuck in flexible solve... while Mamba just installs your packages and you can then get back to work.

https://github.com/mamba-org/mamba

**Comment by Jose-Matsuda** [comment]
Funnily enough I think what we base our images off of do use [mamba](https://github.com/jupyter/docker-stacks/blob/b8d617dc0568d60f6583c42f989da51ec80e9af6/datascience-notebook/Dockerfile#L38) and following all the `FROM`'s does lead us to [installing mamba](https://github.com/jupyter/docker-stacks/blob/b8d617dc0568d60f6583c42f989da51ec80e9af6/docker-stacks-foundation/Dockerfile#L91) and they have [switched off of using conda install](https://github.com/jupyter/docker-stacks/pull/1441)

**Comment by Souheil-Yazji** [comment]
Done!
