### ISSUE TITLE
Investigate Compatibility with Docker Buildkit 2

### ISSUE THREAD

**Issue by Souheil-Yazji** [StatCan/aaw-kubeflow-containers#509]
### Context
https://docs.docker.com/build/buildkit/
https://github.com/StatCan/aaw-kubeflow-containers/pull/508

### Value
Assuming the benefits mentioned in the Docker docs are realized, we may see a large change in the build speeds of our images. This would be very beneficial in the long run in terms of improving dev turn-around time.
Also, we should transition away from legacy build tools for:
1- remaining up-to-date with the technology
2- insuring we're not eventually caught in a deprecation window

**Comment by vexingly** [comment]
We should also investigate if we can use the official docker github actions, which may be optimized and perform better.

See: https://github.com/marketplace/actions/build-and-push-docker-images

**Comment by bryanpaget** [comment]
I noticed this in the Github Actions logs:

```
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            BuildKit is currently disabled; enable it by removing the DOCKER_BUILDKIT=0
            environment-variable.
```

https://github.com/StatCan/aaw-kubeflow-containers/actions/runs/5943984043/job/16120310315#step:13:52

**Comment by Souheil-Yazji** [comment]
> I noticed this in the Github Actions logs:
> 
> ```
> DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
>             BuildKit is currently disabled; enable it by removing the DOCKER_BUILDKIT=0
>             environment-variable.
> ```
> 
> https://github.com/StatCan/aaw-kubeflow-containers/actions/runs/5943984043/job/16120310315#step:13:52

Seems like the clock is ticking and that's scary. I'd say this is a very high priority item then!

**Comment by Souheil-Yazji** [comment]
### Using the Github Docker Action
After doing some research on this, there will need to be a large bit of refactoring for our current actions. I'm not sure if it's 100% possible, as I don't think we can specify the `Notebook Matrix` into the `Docker Build` action's context. The action uses the default git context but a subdir can be specified with [BuildKit v0.9.0](https://github.com/moby/buildkit/releases/tag/v0.9.0).

### Buildkit + Buildx
We are now successfully using these tools, which is a good step forward. I didn't observe a drastic change in build times as we don't have consistent metrics anyways, and the build logs aren't retained for a long duration. I think once we clean up up the docker images with https://github.com/StatCan/aaw/issues/1822, we should see drastic improvement in space + time. 

### Other comments
I did notice that there is a large number of dependency conflicts which need to be resolved, taking form in base images vs our images installing different packages. This is a large contributor to the ballooning of our images, and dependency resolution is probably contributing hugely to build times. 
For example: 
This https://github.com/StatCan/aaw-kubeflow-containers/blob/master/output/jupyterlab-pytorch/Dockerfile#L170 and https://github.com/StatCan/aaw-kubeflow-containers/blob/master/output/jupyterlab-pytorch/Dockerfile#L387, are duplicates and add a layer. 

This https://github.com/StatCan/aaw-kubeflow-containers/blob/master/output/jupyterlab-pytorch/Dockerfile#L345 runs on a combination of pip and conda, and the pip commands execute without caching and the [dependency resolver not working](https://github.com/StatCan/aaw-kubeflow-containers/actions/runs/6086398776/job/16512703184#step:14:2081), which mostlikely causes a huge amount of package deps to be re-pulled/built. This step not-surprisingly takes the longest to run.

**Comment by vexingly** [comment]
Did a bit of testing of buildx here https://github.com/StatCan/aaw-kubeflow-containers/pull/516 but still running into some space constraints but otherwise it just requires the build command to be updated a bit and the buildx builder to be created.

For performance improvement by far the simplest and quickest would be to cache the docker layers between runs (at least on the same branch if not between branches as well). However space is required to store the layers even temporarily to use github caching, which we do not have. Buildkit does support using an external registry for layer caching, so we could use that as a good compromise (this would require additional storage and network usage however).

**Comment by Souheil-Yazji** [comment]
@vexingly yeah, the setup-build-x step isn't the problem, but I definitely thought using the ` uses: docker/build-push-action@v4` action is what you were trying to do. I think if you branch from this [commit](https://github.com/StatCan/aaw-kubeflow-containers/pull/498/commits/efec2c15b13be2ece20b246519cdc60153936fc6), you'll be able to successfully build with the buildkit and the build-x step.
