### ISSUE TITLE
Investigate source of large R related files in remote-desktop and remove them.

### ISSUE THREAD

**Issue by bryanpaget** [StatCan/aaw-kubeflow-containers#515]
These files appear in the file-manager and the numbers correspond to rstudio-deskop/rstudio-server version numbers. Could be related to #513 

![image](https://github.com/StatCan/aaw-kubeflow-containers/assets/8212170/8482222a-139b-4429-9f72-38ef7c97e1aa)

**Comment by bryanpaget** [comment]
This was caused by rstudio-server and rstudio-desktop crashing. See: 

- https://github.com/StatCan/aaw-kubeflow-containers/issues/513

**Comment by chuckbelisle** [comment]
Not an issue as this is normal behaviour
