### ISSUE TITLE
Feature: Grist Spreadsheets app

### ISSUE THREAD

**Issue by bryanpaget** [StatCan/aaw-kubeflow-containers#559]
In addition to tools that can be run from the JupyterLab Notebook (mitosheets and pygwalker for instance) there are other tools we could host for users on Kubeflow. Grist is an interesting collaborative Spreadsheet app. This could be a great addition to the AAW if someone is looking for a powerful spreadsheet app.

- https://github.com/gristlabs/grist-core

**Comment by Souheil-Yazji** [comment]
Better to push this towards the zone, and then if applicable, we can implement on aaw as well.
