### ISSUE TITLE
Feature: LocalAI (openAI API compatible self-hosted models)

### ISSUE THREAD

**Issue by bryanpaget** [StatCan/aaw-kubeflow-containers#568]
LocalAI is the free, Open Source OpenAI alternative. LocalAI act as a drop-in replacement REST API that’s compatible with OpenAI API specifications for local inferencing. It allows you to run LLMs, generate images, audio (and not only) locally or on-prem with consumer grade hardware, supporting multiple model families that are compatible with the ggml format. Does not require GPU. It is maintained by [mudler](https://github.com/mudler).

- https://localai.io/

**Comment by Souheil-Yazji** [comment]
I would put this under AI tools for the zone as well.
