### ISSUE TITLE
Fix aaw-kubeflow-containers makefile and make instructions

### ISSUE THREAD

**Issue by bryanpaget** [StatCan/aaw-kubeflow-containers#578]
I updated the github actions a while ago as part of tickets:

- https://github.com/StatCan/aaw-kubeflow-containers/pull/501
- https://github.com/StatCan/aaw-kubeflow-containers/pull/491

This has made our Makefile conformant to Github's standards but presents a problem when building images locally.

```
(base) pagetbr@l-pagetbr-2:~/aaw-kubeflow-containers$ make build/rstudio
# End repo with exactly one trailing slash, unless it is empty
REPO=$(echo "k8scc01covidacr.azurecr.io" | sed 's:/*$:/:' | sed 's:^\s*/*\s*$::') &&\
IMAGE_NAME="${REPO}rstudio:master" && \
DOCKER_BUILDKIT=0 docker build  --rm --force-rm -t $IMAGE_NAME ./output/rstudio && \
echo -n "Built image $IMAGE_NAME of size: " && \
docker images $IMAGE_NAME --format "{{.Size}}" && \
echo "full_image_name=$IMAGE_NAME" >>  && \
echo "image_tag=master" >>  && \
echo "image_repo=${REPO}" >> 
/bin/sh: 6: Syntax error: "&&" unexpected
make: *** [Makefile:206: build/rstudio] Error 2
(base) pagetbr@l-pagetbr-2:~/aaw-kubeflow-containers$ 
```

**Comment by Souheil-Yazji** [comment]
One thing I want you to look at in particular is `DOCKER_BUILDKIT=0`, not sure if that's relevant/causes conflict.

**Comment by EveningStarlight** [comment]
Looked into `DOCKER_BUILDKIT=0`, and it's going to be a more complicated fix. 
Being spun off into a new issue.
