### ISSUE TITLE
Add Commenting Extension

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/aaw-kubeflow-containers#58]
It seems to be working now. I will get it added.

**Comment by chritter** [comment]
@blairdrummond I assume this is the Jupyter extension? @frazs This would be great to have on ml-workspace images for  reviewing of work.

**Comment by frazs** [comment]
@blairdrummond What extension is this? Does it make sense on remote-desktop?

**Comment by bryanpaget** [comment]
@blairdrummond This extensions?

https://github.com/jupyterlab/jupyterlab-commenting

**Comment by brendangadd** [comment]
Closing as stale.
