### ISSUE TITLE
Fix Remote Desktop Build Issue

### ISSUE THREAD

**Issue by Souheil-Yazji** [StatCan/aaw-kubeflow-containers#660]
- [x] Try to build remote desktop image using makefile
- [x] This will break at the Quarto Installation Step https://github.com/StatCan/aaw-kubeflow-containers/blob/master/output/remote-desktop/Dockerfile#L217-L222
- [x] resolve install issue in remote desktop without impacting the other images, this might involve changing the layer where quarto is installed

**Comment by jacek-dudek** [comment]
Replicated build error on my issue branch.
Looking into breaking down the bash command to figure out exact step that breaks things.

**Comment by jacek-dudek** [comment]
Fixed quarto related issues with the remote-desktop build.
One issue was the QUARTO_VERSION argument not correctly resolving. Replaced ARG directive with ENV directive and that worked.

Found another issue related to quarto.
There was already a file named quarto in /usr/local/bin.
It's a symbolic link to some other quarto installation. Didn't check if link is valid.

Here's output from the relevant build:
...
Step 46/144 : RUN sudo ls /usr/local/bin
 ---> Running in baebf6c44eac
aaw-suspend-server.sh
argo
debugpy
...
quarto <-----
...
wgrib2
wsdump
 ---> Removed intermediate container baebf6c44eac
 ---> a6f069a2ee55
Step 47/144 : RUN sudo file /usr/local/bin/quarto
 ---> Running in ada4dfead745
/usr/local/bin/quarto: symbolic link to /usr/lib/rstudio-server/bin/quarto/bin/quarto
 ---> Removed intermediate container ada4dfead745
 ---> 97ecbc1fa1d9
Step 48/144 : RUN sudo mv ./quarto-${QUARTO_VERSION} /usr/local/bin/quarto
 ---> Running in 6dce158247b7
mv: cannot overwrite non-directory '/usr/local/bin/quarto' with directory './quarto-1.5.52'
 ---> Removed intermediate container 6dce158247b7
The command '/bin/sh -c sudo mv ./quarto-${QUARTO_VERSION} /usr/local/bin/quarto' returned a non-zero code: 1
make: *** [Makefile:206: build/remote-desktop] Error 1
Error: Process completed with exit code 2.

I resolved it by running rm -f quarto before copying the extracted archive.

**Comment by jacek-dudek** [comment]
Now I'm getting another error that appears to be unrelated to quarto. It might have something to do with node package manager installation. I'll be breaking the shell command that's throwing the error down into steps to figure it out. Relevant output from the build:

The command '/bin/sh -c cd $RESOURCES_PATH     && mkdir -p $HOME/.local/share     && mkdir -p $VSCODE_DIR/extensions     && VS_PYTHON_VERSION="2020.5.86806"     && wget --quiet --no-check-certificate https://github.com/microsoft/vscode-python/releases/download/$VS_PYTHON_VERSION/ms-python-release.vsix     && echo "${SHA256py} ms-python-release.vsix" | sha256sum -c -     && bsdtar -xf ms-python-release.vsix extension     && rm ms-python-release.vsix     && mv extension $VSCODE_DIR/extensions/ms-python.python-$VS_PYTHON_VERSION     && VS_FRENCH_VERSION="1.68.3"     && VS_LOCALE_REPO_VERSION="1.68.3"     && git clone -b release/$VS_LOCALE_REPO_VERSION https://github.com/microsoft/vscode-loc.git     && cd vscode-loc     && npm install -g --unsafe-perm vsce@1.103.1     && cd i18n/vscode-language-pack-fr     && vsce package     && bsdtar -xf vscode-language-pack-fr-$VS_FRENCH_VERSION.vsix extension     && mv extension $VSCODE_DIR/extensions/ms-ceintl.vscode-language-pack-fr-$VS_FRENCH_VERSION     && cd ../../../     && rm -fr vscode-loc     && npm uninstall -g vsce     && fix-permissions $XDG_DATA_HOME     && clean-layer.sh' returned a non-zero code: 1
make: *** [Makefile:206: build/remote-desktop] Error 1
Error: Process completed with exit code 2.

**Comment by jacek-dudek** [comment]
Currently trying to figure out why I cannot cd into a directory that appears to be there during installation of vscode language pack extension.

Output from most recent build attempt:
Step 87/171 : RUN pwd
 ---> Running in 72b95ac20968
/tmp
 ---> Removed intermediate container 72b95ac20968
 ---> cb6ba14210e3
Step 88/171 : RUN tree -d
 ---> Running in 9a9cab7e73b1
.
└── vscode-loc
    ├── i18n
    │   ├── vscode-language-pack-cs
    │   │   └── translations
    │   │       └── extensions
    │   ├── vscode-language-pack-de
    │   │   └── translations
    │   │       └── extensions
    │   ├── vscode-language-pack-es
    │   │   └── translations
    │   │       └── extensions
    │   ├── vscode-language-pack-fr
    │   │   └── translations
    │   │       └── extensions
    │   ├── vscode-language-pack-it
    │   │   └── translations
    │   │       └── extensions
    │   ├── vscode-language-pack-ja
    │   │   └── translations
    │   │       └── extensions
    │   ├── vscode-language-pack-ko
    │   │   └── translations
    │   │       └── extensions
    │   ├── vscode-language-pack-pl
    │   │   └── translations
    │   │       └── extensions
    │   ├── vscode-language-pack-pt-BR
    │   │   └── translations
    │   │       └── extensions
    │   ├── vscode-language-pack-qps-ploc
    │   │   └── translations
    │   │       └── extensions
    │   ├── vscode-language-pack-ru
    │   │   └── translations
    │   │       └── extensions
    │   ├── vscode-language-pack-tr
    │   │   └── translations
    │   │       └── extensions
    │   ├── vscode-language-pack-zh-hans
    │   │   └── translations
    │   │       └── extensions
    │   └── vscode-language-pack-zh-hant
    │       └── translations
    │           └── extensions
    └── media

45 directories
 ---> Removed intermediate container 9a9cab7e73b1
 ---> a68c50acdc15
Step 89/171 : RUN cd ./vscode-loc
 ---> Running in ae8362012b33
 ---> Removed intermediate container ae8362012b33
 ---> c8e7c8f5d213
Step 90/171 : RUN pwd
 ---> Running in a571761e3949
/tmp

**Comment by jacek-dudek** [comment]
Resolved the issue of being unable to cd into the language pack directory (/tmp/vscode-loc/i18n/vscode-language-pack-fr) by replacing the cd commands with WORKDIR directives.

Now trying to work out a nodejs runtime error that the vsce utility throws:
Step 93/172 : RUN vsce package
 ---> Running in 3cd69db2f62d
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'node:stream'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/vsce/node_modules/parse5-parser-stream/dist/cjs/index.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
 ---> Removed intermediate container 3cd69db2f62d
The command '/bin/sh -c vsce package' returned a non-zero code: 1
make: *** [Makefile:206: build/remote-desktop] Error 1
Error: Process completed with exit code 2.

**Comment by jacek-dudek** [comment]
Reviewed some earlier npm related warnings in the build logs. Many are version related:
npm WARN notsup Unsupported engine for cheerio@1.0.0: wanted: {"node":">=18.17"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: cheerio@1.0.0
npm WARN notsup Unsupported engine for tmp@0.2.3: wanted: {"node":">=14.14"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: tmp@0.2.3
npm WARN notsup Unsupported engine for undici@6.19.8: wanted: {"node":">=18.17"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: undici@6.19.8
npm WARN notsup Unsupported engine for whatwg-mimetype@4.0.0: wanted: {"node":">=18"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: whatwg-mimetype@4.0.0
npm WARN notsup Unsupported engine for whatwg-encoding@3.1.1: wanted: {"node":">=18"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: whatwg-encoding@3.1.1    

Current remote desktop is based on rocker/geospatial:4.2.1which has its apt sources set conservatively, because subsequent apt install commands for nodejs and npm gets versions 10.19 and 6.14 respectively.

Trying instead to install a local version of nodejs from binary archive at: https://nodejs.org/dist/v20.17.0/node-v20.17.0-linux-x64.tar.xz and extracting and setting it up. Then using npm to install the current version of the vsce tool to use that local installation.

**Comment by jacek-dudek** [comment]
We unpinned the rocker base image version and tried to build with that.
    Got a apt-get install error not finding gvfs-bin package.
        Work around by globbing gvfs* to get whatever is there.
    Got another apt-get install error with zlibc.
        Worked around that using another glob for zlibc*

    Now we're getting a node runtime error again with the current version of vsce.

    Step 84/168 : RUN npm install -g @vscode/vsce
     ---> Running in b553753b6ff3
    npm WARN EBADENGINE Unsupported engine {
    npm WARN EBADENGINE   package: '@vscode/vsce@3.1.1',
    npm WARN EBADENGINE   required: { node: '>= 20' },
    npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
    npm WARN EBADENGINE }

    Let's try the older specific version, maybe it will work with the unpinned base image.
    
    With the older vsce version I'm getting the same runtime error as before.

    Step 89/168 : RUN vsce package
     ---> Running in 9f78045dace7
    internal/modules/cjs/loader.js:818
      throw err;
      ^
    Error: Cannot find module 'node:stream'
    Require stack:
    - /usr/local/lib/node_modules/vsce/node_modules/parse5-parser-stream/dist/cjs/index.js
    - /usr/local/lib/node_modules/vsce/node_modules/cheerio/dist/commonjs/index.js
    - /usr/local/lib/node_modules/vsce/out/package.js
    - /usr/local/lib/node_modules/vsce/out/main.js
    - /usr/local/lib/node_modules/vsce/vsce
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
        at Function.Module._load (internal/modules/cjs/loader.js:667:27)
        at Module.require (internal/modules/cjs/loader.js:887:19)
        at require (internal/modules/cjs/helpers.js:85:18)
        at Object.<anonymous> (/usr/local/lib/node_modules/vsce/node_modules/parse5-parser-stream/dist/cjs/index.js:4:23)
        at Module._compile (internal/modules/cjs/loader.js:999:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
        at Module.load (internal/modules/cjs/loader.js:863:32)
        at Function.Module._load (internal/modules/cjs/loader.js:708:14)
        at Module.require (internal/modules/cjs/loader.js:887:19) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/usr/local/lib/node_modules/vsce/node_modules/parse5-parser-stream/dist/cjs/index.js',
        '/usr/local/lib/node_modules/vsce/node_modules/cheerio/dist/commonjs/index.js',
        '/usr/local/lib/node_modules/vsce/out/package.js',
        '/usr/local/lib/node_modules/vsce/out/main.js',
        '/usr/local/lib/node_modules/vsce/vsce'
      ]
    }

**Comment by jacek-dudek** [comment]
Resolved the vscode language pack installation issue. Followed these steps:
Create a root directory /tmp/vscode-language-pack-install for the installation process.
Download latest stable version of node and utilities from an archive.
Clone vscode language extension packs repository from github.
Create symbolic links: /usr/bin/node, /usr/bin/npm, /usr/bin/npx to the corresponding binaries in the node installation.
Move to root node installation directory and run npm install @vscode/vsce.
Move to the subdirectory of the language pack repository that holds the french language pack.
Run npx <fully qualified path to vsce directory under node_modules in node installation directory> package.
This will create the language pack archive.
Extract archive using tar and move extracted archive to appropriate sub-directory in vscode installation.

**Comment by jacek-dudek** [comment]
Now we're getting a build error during installation of R Studio desktop:
Reading state information... 99%
 This package is uninstallable
Dependency is not satisfiable: libssl1.0.0|libssl1.0.2|libssl1.1

Reading state information... Done
 ---> Removed intermediate container c77a5ba3de69
The command '/bin/sh -c /bin/bash $RESOURCES_PATH/r-studio-desktop.sh &&      apt-get clean &&      rm -rf /var/lib/apt/lists' returned a non-zero code: 1
make: *** [Makefile:206: build/remote-desktop] Error 1
Error: Process completed with exit code 2.

**Comment by jacek-dudek** [comment]
Resolved the package install error related to libssl by re-pinning the version to the rocker base image.
        Step 177/177 : CMD ["start-remote-desktop.sh"]
         ---> Running in 826a126dab33
         ---> Removed intermediate container 826a126dab33
         ---> e10a895efb24
        Successfully built e10a895efb24
        Successfully tagged localhost:5000/remote-desktop:aaw-660
        Built image localhost:5000/remote-desktop:aaw-660 of size: 16.7GB
        ##[debug]Set output full_image_name = localhost:5000/remote-desktop:aaw-660
        ##[debug]Set output image_tag = aaw-660
        ##[debug]Set output image_repo = localhost:5000/
        ##[debug]Finishing: Build image

**Comment by jacek-dudek** [comment]
Now I'm getting an error during the test phase:
/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/json/decoder.py:355: JSONDecodeError
------------------------------ Captured log setup ------------------------------
INFO     helpers:helpers.py:51 Starting container localhost:5000/remote-desktop:aaw-660 ...
INFO     conftest:conftest.py:104 Running localhost:5000/remote-desktop:aaw-660 with args {'detach': True, 'ports': {'8888/tcp': 8888}, 'environment': {'NB_PREFIX': '/notebook/username/notebookname'}, 'tty': True} ...
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:None "POST /v1.45/containers/create HTTP/11" 201 88
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:None "GET /v1.45/containers/4a8ad5b1defff08c3bd679244335b5380f6591f360aeadeefe3a4362c54e932d/json HTTP/11" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:None "POST /v1.45/containers/4a8ad5b1defff08c3bd679244335b5380f6591f360aeadeefe3a4362c54e932d/start HTTP/11" 204 0
INFO     helpers:helpers.py:88 Grabing the list of specifications ...
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:None "POST /v1.45/containers/4a8ad5b1defff08c3bd679244335b5380f6591f360aeadeefe3a4362c54e932d/exec HTTP/11" 201 74
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:None "POST /v1.45/exec/2d7c6bc4b397ed78fd7faf93a89c4936058e21032d8643c09319888ac2178cd0/start HTTP/11" 101 0
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:None "GET /v1.45/exec/2d7c6bc4b397ed78fd7faf93a89c4936058e21032d8643c09319888ac2178cd0/json HTTP/11" 200 449
=========================== short test summary info ============================
ERROR tests/general/test_packages.py::test_python_packages - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR tests/general/test_packages.py::test_r_packages - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
========================= 1 passed, 2 errors in 7.43s ==========================
make: *** [Makefile:265: test/remote-desktop] Error 1
Error: Process completed with exit code 2.
##[debug]Finishing: Test image

**Comment by Souheil-Yazji** [comment]
https://github.com/StatCan/aaw-kubeflow-containers/issues/663
