### ISSUE TITLE
Remote-Desktop: Investigate JSONDecodeError in Build

### ISSUE THREAD

**Issue by jacek-dudek** [StatCan/aaw-kubeflow-containers#663]
The python based test suite throws a JSONDecodeError. Here's the output from the build process:
/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/json/decoder.py:355: JSONDecodeError
------------------------------ Captured log setup ------------------------------
INFO helpers:helpers.py:51 Starting container localhost:5000/remote-desktop:aaw-660 ...
INFO conftest:conftest.py:104 Running localhost:5000/remote-desktop:aaw-660 with args {'detach': True, 'ports': {'8888/tcp': 8888}, 'environment': {'NB_PREFIX': '/notebook/username/notebookname'}, 'tty': True} ...
DEBUG urllib3.connectionpool:connectionpool.py:546 http://localhost:None "POST /v1.45/containers/create HTTP/11" 201 88
DEBUG urllib3.connectionpool:connectionpool.py:546 http://localhost:None "GET /v1.45/containers/4a8ad5b1defff08c3bd679244335b5380f6591f360aeadeefe3a4362c54e932d/json HTTP/11" 200 None
DEBUG urllib3.connectionpool:connectionpool.py:546 http://localhost:None "POST /v1.45/containers/4a8ad5b1defff08c3bd679244335b5380f6591f360aeadeefe3a4362c54e932d/start HTTP/11" 204 0
INFO helpers:helpers.py:88 Grabing the list of specifications ...
DEBUG urllib3.connectionpool:connectionpool.py:546 http://localhost:None "POST /v1.45/containers/4a8ad5b1defff08c3bd679244335b5380f6591f360aeadeefe3a4362c54e932d/exec HTTP/11" 201 74
DEBUG urllib3.connectionpool:connectionpool.py:546 http://localhost:None "POST /v1.45/exec/2d7c6bc4b397ed78fd7faf93a89c4936058e21032d8643c09319888ac2178cd0/start HTTP/11" 101 0
DEBUG urllib3.connectionpool:connectionpool.py:546 http://localhost:None "GET /v1.45/exec/2d7c6bc4b397ed78fd7faf93a89c4936058e21032d8643c09319888ac2178cd0/json HTTP/11" 200 449
=========================== short test summary info ============================
ERROR tests/general/test_packages.py::test_python_packages - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR tests/general/test_packages.py::test_r_packages - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
========================= 1 passed, 2 errors in 7.43s ==========================
make: *** [Makefile:265: test/remote-desktop] Error 1
Error: Process completed with exit code 2.
##[debug]Finishing: Test image

**Comment by EveningStarlight** [comment]
the `_execute_command` function is failing, so a JSON isn't being passed to the `_packages_from_json` function

The error being passed through is
```
OCI runtime exec failed: exec failed: unable to start container process: exec: "conda": executable file not found in $PATH: unknown
```

**Comment by EveningStarlight** [comment]
Confirmed that conda is not installed on the remote-desktop container

**Comment by EveningStarlight** [comment]
Confirmed that conda is on the path of a different container. (jupyterlab-tensorflow)

**Comment by EveningStarlight** [comment]
PR merged
