### ISSUE TITLE
Go over dockerfile best practices in context of remote desktop and other images

### ISSUE THREAD

**Issue by jacek-dudek** [StatCan/aaw-kubeflow-containers#664]
Go over RUN, chaining commands together, ARG versus ENV, WORKDIR, sudo etc..

- [ ] Review Docker best practices
- [ ] Create summary document for internal consumption (include references)

**Comment by jacek-dudek** [comment]
Reviewed instances in remote desktop image where I was forced to look for workarounds to ARG directives not being set and where cd command was not executing correctly. I will book a short period in elab to present and ask for insight.

**Comment by Souheil-Yazji** [comment]
Not Done
