### ISSUE TITLE
Trivy out of date

### ISSUE THREAD

**Issue by EveningStarlight** [StatCan/aaw-kubeflow-containers#671]
Trivy is out of date, and so it's scan is missing critical vulnerabilities. 

I was playing with updating Trivy to see if I could solve the `TOOMANYREQUESTS` error that we frequently experience. 
On the new version, the scan is more reliable, and found vulnerabilities in our images that the previous version wasn't catching. 
See the failed builds in https://github.com/StatCan/aaw-kubeflow-containers/pull/670 for more info on the scan. 

Should have a push for this soon as well.

**Comment by Souheil-Yazji** [comment]
I would do this work for 1 repo, then update to all other repos which leverage trivy after.
